---
- name: Create file with my module
  my_own_namespace.yandex_cloud_elk.my_own_module:
    path: "{{ file_path | default('/tmp/default.txt') }}"
    content: "{{ file_content | default('Hello from role!') }}"
